### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by nikhar-abbas**
# Refactor
Some large updates to re-factor a number of dependencies that the ROSCO toolbox has had thus far. The main motivation for this is to ease the use of ROSCO as a stand-alone tool. 

### Major changes
- remove dependency on [WIES's Aeroelasticse](https://github.com/WISDEM/WEIS/tree/master/weis/aeroelasticse). For now, the Openfast I/O files and casegen-related scripts have been copied into a new folder in the ROSCO toolbox called ofTools. Over time, I think we can do some re-org to clean up and ease the workflow in these tools for controls and ROSCO specific purposes. 

### Minor Changes
- None, yet

## To-Do list
Here's a list of items we need before this PR is ready to be merged. They can be added to the major and minor changes above as they get checked off.
- [x] Move plotting from ROSCO_toolbox/utilities.py to ofTools 
- [x] Test tuning scripts
- [x] Add to ofTools README to provide better descriptions of the scripts
- [x] Update primary README to accommodate all changes
- [x] Push BAR model
- [x] Check examples
- [x] Check ROSCO_walkthrough.ipynb
- [ ] Get rid of pCrunch dependency
- [x] Update setup.py to compile ROSCO better

This refactor will also necessitate changes to [pCrunch](https://github.com/nrel/pCrunch) and [weis](https://github.com/wisdem/weis).

#### Some notes on possibilities:
- The DISCON read/write function is pretty non-congruous with the aeroelasticse FAST_reader and FAST_writer functions. Good practice would be to consolidate all of these into a single function that works consistently, but this would involve some fairly significant restructuring to how the controller and turbine classes are handled or something like that (maybe a good thing anyways). This would end up trickling down to changes in how the read_DISCON and write_DISCON functions work, and call for updates to WEIS itself. Not a big deal, just should be kept in mind.

### CODE REVIEW

**Comment by nikhar-abbas** [comment]
I removed the ROSCO submodule in b6295b3 and added a section to check for the conda-forge distribution of ROSCO in the setup.py file in 5689dbe.

**Comment by dzalkind** [comment]
There are some issues in the ROSCO_testing scripts.  They want to use pCrunch and pCrunch wants to use ROSCO_toolbox utilities.  Do we want to remove dependency on pCrunch while that is being revamped?

**Comment by nikhar-abbas** [comment]
> There are some issues in the ROSCO_testing scripts. They want to use pCrunch and pCrunch wants to use ROSCO_toolbox utilities. Do we want to remove dependency on pCrunch while that is being revamped?

I think it might be smart to get a parallel pCrunch branch going to call the new ROSCO toolbox utilities, and eventually coordinate their merges into their respective develop/master branches.

**Comment by dzalkind** [comment]
This looks good. I'd like to merge it into develop.  There is still one place with a pCrunch dependency, but I don't think it is used often: `generate_rotperf_fast()` in `turbine.py`.

**Pull request merged**
